### ISSUE TITLE
Usage of both constructor and initialize function

### ISSUE THREAD

**Issue by demis1997** [tokamak-network/gem-nft-contract#27]
`src/L2/GemFactory.sol`

Is there a reason you are using both a constructor and an initialize function?
You are setting `DEFAULT_ADMIN_ROLE` in one and checking `owner` role in the other, you should consider renaming them or using just one of the two.

Example:
Current:
```

    constructor(address coordinator) ERC721("GemSTON", "GEM") DRBConsumerBase(coordinator) {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        drbcoordinator = coordinator;
    }
    
    
    function initialize(
        address _wston, 
        address _ton,
        address _treasury,  
        uint256 _CommonGemsValue,
        uint256 _RareGemsValue,
        uint256 _UniqueGemsValue,
        uint256 _EpicGemsValue,
        uint256 _LegendaryGemsValue,
        uint256 _MythicGemsValue
    )
    external onlyOwner {
```

Fix:
Use either initialize or constructor instead of both
Double check if the access control is correct

**Comment by mehdi-defiesta** [comment]
This is intended since the constructor is mandatory (for the access control and the beacon node consumer) and the owner must initialize these variables himself. This has no impact on contract.

**Comment by demis1997** [comment]
Noted, I will close the issue then
