### ISSUE TITLE
[Code review: Contract Bugs]: Recommended use of modifier

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#31]
### Describe    

 https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L1/L1WrappedStakedTONFactory.sol#L24-L26

### Impact
- Modifier is usually used to check whether the requirements are met before executing the function.
- When the same require statement is used multiple times, using a modifier is more intuitive and helps with code management.

### Recommendation

```
modifier nonZeroAddress(address _address) {
        require(_address != address(0), "zeroAddress")
        _;
}

function createWSTONToken(
        address _layer2Address,
        address _depositManager,
        address _seigManager,
        string memory _name,
        string memory _symbol
    ) external onlyOwner 
       nonZeroAddress(_layer2Address) 
       nonZeroAddress(_layer2Address) 
       nonZeroAddress(_layer2Address) 
       returns(address) 
    {  
   

```

**Comment by mehdi-defiesta** [comment]
modification passed : [Link](https://github.com/tokamak-network/gem-nft-contract/commit/425fd51e9303aa060ff716418fd697531ebb86c9)

**Comment by Zena-park** [comment]
I confirmed, thank you.
