### ISSUE TITLE
[Code review: Contract Bugs]: all possible WithdrawalRequests at once on 'claimWithdrawal'

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#35]
### Describe the bug

If you make multiple 'requestWithdrawal', **you must conduct each claim separately** even though all requestWithdrawals have passed the delay block and are therefore eligible for a claim.

### Impact

It uses more gas.
The user must separately check how many more claims he/she needs to make, 
and may not understand that he/she needs to make multiple claims.

### Recommendation

When executing claimWithdrawal(claimWithdrawalTo), you should be able to claim everything(withdrawalRequests) that is claimable at once.

**Comment by mehdi-defiesta** [comment]
thanks @Zena-park I've created two different functions for claiming requests. One is claiming all claimable requests and the seconds claims only one request related to a specific index. Moreover, I've created two view functions `getTotalClaimableAmountByUser` and `getTotalClaimableAmount`. 

Here is the code [update](https://github.com/tokamak-network/gem-nft-contract/blob/7e23fb8b1561019dfc144a5f93fb5286a7a913c0/src/L1/L1WrappedStakedTON.sol#L276)

**Comment by Zena-park** [comment]
- [getTotalClaimableAmount](https://github.com/tokamak-network/gem-nft-contract/blob/7e23fb8b1561019dfc144a5f93fb5286a7a913c0/src/L1/L1WrappedStakedTON.sol#L416-L424)
If there are many users, it may take too much time to retrieve the results. (The more users the service has, the worse the quality of the function. )
If it is used in a service, it may cause quality degradation due to response speed delay, so
It is recommended to delete the function if it is not absolutely necessary.

- [getTotalClaimableAmountByUser](https://github.com/tokamak-network/gem-nft-contract/blob/7e23fb8b1561019dfc144a5f93fb5286a7a913c0/src/L1/L1WrappedStakedTON.sol#L441C14-L441C43)
  - convert  visibility 'public' to  'external' 
  - totalClaimableAmount defaults to 0, so you don't need to reassign 0.
  - It is recommended to use [function return variables](https://docs.soliditylang.org/en/v0.8.27/contracts.html#return-variables).

**Comment by mehdi-defiesta** [comment]
Thanks @Zena-park . It is [updated](https://github.com/tokamak-network/gem-nft-contract/commit/2540ee12b1b81fd86ed77fb42daafb4bae864a64)
