### ISSUE TITLE
[Code review: Contract Bugs]: Recommend to check the use of TON when depositing to depositManager

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#36]
### Describe the bug

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L1/L1WrappedStakedTON.sol#L98-L109

If you do wton approve and make a deposit,
It seems that using TON.approveAndCall will save more gas fees.

It would be good to compare gas fees.

**Comment by mehdi-defiesta** [comment]
@Zena-park check [this](https://github.com/tokamak-network/gem-nft-contract/issues/32#issuecomment-2383076077)

**Comment by Zena-park** [comment]
It is discussed in #32.
