### ISSUE TITLE
[Code review: Contract Bugs]: updateSeigniorage() function error

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#37]
### Describe the bug

I think it gets an error when executing updateSeigniorage().

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L1/L1WrappedStakedTON.sol#L190-L193

The caller of SeigManager's updateSeigniorage() function should be coinage.
https://github.com/tokamak-network/ton-staking-v2/blob/2cc9016520e1c08bd41958a764f8af5e3f324d72/contracts/stake/managers/SeigManagerV1_2.sol#L429-L432

So this contract is not coinage, so it seems to throw an error.

### Recommendation

Use the SeigManager's [updateSeigniorageLayer](https://github.com/tokamak-network/ton-staking-v2/blob/2cc9016520e1c08bd41958a764f8af5e3f324d72/contracts/stake/managers/SeigManagerV1_2.sol#L627-L631) function.

```
   function updateSeigniorage() external returns(bool) { 
        return ISeigManager(seigManager).updateSeigniorageLayer(layer2Address);
    }

```

**Comment by mehdi-defiesta** [comment]
thanks @Zena-park You are right. I think it was possible before the last upgrade. I passed the modification. Here is the [link](https://github.com/tokamak-network/gem-nft-contract/commit/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225).

**Comment by Zena-park** [comment]
I confirmed. Thank you.
