### ISSUE TITLE
[Code review: Contract Bugs]: need the view total claimable(withdrawal) amount function

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#38]
### Describe the bug

We need a function to query how much total claimable amount is currently available(what has passed the delay blocks already).
If the service interface(UI) is provided, this function would be desperately needed.

**Comment by mehdi-defiesta** [comment]
Thanks @Zena-park. Please check this [issue](https://github.com/tokamak-network/gem-nft-contract/issues/35).

**Comment by Zena-park** [comment]
I confirmed. Thank you.
