### ISSUE TITLE
[Code review: Contract Bugs]: L1WrappedStakedTON and L1WrappedStakedTONProxy have different memory designs.

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#39]
### Describe the bug

- L1WrappedStakedTON and L1WrappedStakedTONProxy have different memory designs.
   Please also check other contracts.  
      -  MarketPlace / MarketPlaceProxy 
      - RandomPack / RandomPackProxy
      - WstonSwapPool / ProxyWstonSwapPool  
   
The first storage area of ​​L1WrappedStakedTONProxy has a value of
   `bool public pauseProxy;`
   
, and the first storage area of ​​L1WrappedStakedTON has a value of
    `address private _owner;`

- L1WrappedStakedTONProxy

    https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L1/L1WrappedStakedTONProxy.sol#L11

    https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/proxy/ProxyL1WrappedStakedTON.sol#L11-L16

    https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/proxy/ProxyStorage.sol#L4-L9

- L1WrappedStakedTON
https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L1/L1WrappedStakedTON.sol#L20

    https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cceac54953ccda8a9a028d0b9bf4378605fdf67e/contracts/access/Ownable.sol#L20-L22
    ```
    abstract contract Ownable is Context {
    address private _owner;
    ```

**Comment by mehdi-defiesta** [comment]
Thanks @Zena-park . I modified each contract to make the proxy storage on the top of the storage. Here is the [commit](https://github.com/tokamak-network/gem-nft-contract/commit/6df7365921e853dfbfda053d42508c0a13692155)

**Comment by Zena-park** [comment]
Could you please modify your test code to use a proxy? I would like to verify this through testing.

**Comment by mehdi-defiesta** [comment]
I think we have to review the way it is implemented. We must switch from a constructor to an initialize function. However, I am not sure how we could instanciate ERC20 in an initialize function.

**Comment by Zena-park** [comment]
If you want to use OpenZaplin, [this document ](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable) will help you. [openzeppelin-contracts-upgradeable.ERC20](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/tree/master/contracts/token/ERC20) 

Or,  you can design and create your own ERC20 that is upgradable without using OpenZaplin.
 
 Please try it out and if you have any questions, please contact me through the channel.

**Comment by mehdi-defiesta** [comment]
switch from a custom proxy to openzeppelin UUPS. [Here](https://github.com/tokamak-network/gem-nft-contract/blob/codeRelease_apply/src/L1/L1WrappedStakedTON.sol) is L1WrappedStakedTON contract.
I've updated the [factory](https://github.com/tokamak-network/gem-nft-contract/blob/9c00c8b52589441b892ce910cd9595597fd9745d/src/L1/L1WrappedStakedTONFactory.sol#L38) to create a new ERC1967 proxy.

**Comment by mehdi-defiesta** [comment]
@Zena-park

**Comment by Zena-park** [comment]
- The owner of L1WrappedStakedTON(proxy) becomes L1WrappedStakedTONFactory.

- I would appreciate it if you could leave the test execution code.

**Comment by Zena-park** [comment]
If you deploy a new L1WrappedStakedTON every time you run createWSTONToken, you will pay many gas fees.

You can reduce gas by deploying L1WrappedStakedTON and only managing the wstonImplementation address in the L1WrappedStakedTONFactory.

(1) Delete the L1WrappedStakedTON creation code.
https://github.com/tokamak-network/gem-nft-contract/blob/effb21a65c9969221f37581b953362f5c4f2628a/src/L1/L1WrappedStakedTONFactory.sol#L37

(2) Add wstonImplementation storage and create management functions.
 ```
 address public wstonImplementation; 
 
 function setWstonImplementation(address _imp) external onlyOwner { 
        wstonImplementation = _imp;  
    }
 ```

**Comment by mehdi-defiesta** [comment]
thanks @Zena-park . Here is the factory [update](https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L1/L1WrappedStakedTONFactory.sol#L59). I added a parameter in initialize function to assign the owner.

Here is the test execution [code](https://github.com/tokamak-network/gem-nft-contract/blob/codeRelease_apply/test/L1/L1BaseTest.sol): 
```Solidity
l1wrappedstakedtonFactory = address(new L1WrappedStakedTONFactory());
l1WrappedStakedTon = address(new L1WrappedStakedTON());
L1WrappedStakedTONFactory(l1wrappedstakedtonFactory).initialize(wton, ton);
L1WrappedStakedTONFactory(l1wrappedstakedtonFactory).setWstonImplementation(l1WrappedStakedTon);
```

**Comment by Zena-park** [comment]
I confirmed. Thank you.
