### ISSUE TITLE
[Code review: Contract Bugs]: Optimize gas with tightly packing in 'structure'

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#40]
### Describe the bug

It can be packed more tightly.

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/GemFactoryStorage.sol#L15-L27

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/GemFactoryStorage.sol#L29-L36

### Impact

more gas consumption  

### Recommendation

 - struct Gem 
   Reduced from 8~9 slots required to 7 slots required
   
    ```
    struct Gem {
            uint256 tokenId;  
            uint256 gemCooldownPeriod; // gem cooldown before user can start mining
            uint256 miningPeriod; // Mining delay before claiming
            uint256 miningTry; 
            uint256 randomRequestId; // store the random request (if any). it is initially set up to 0
            uint256 value; // 27 decimals
            Rarity rarity; 
            bool isLocked; // Locked if gem is listed on the marketplace
            uint8[4] quadrants; // 4 quadrants
            uint8[2] color; // id of the color
            string tokenURI; // IPFS address of the metadata file 
        }
    
    ```
- struct RequestStatus 
   Reduced from 5 slots required to 4 slots required
   
    ```
    struct RequestStatus {
            uint256 tokenId;
            uint256 randomWord;
            uint256 chosenTokenId;
            bool requested; // whether the request has been made
            bool fulfilled; // whether the request has been successfully fulfilled
            address requester;
        } 
    ```

**Comment by mehdi-defiesta** [comment]
Thank you @Zena-park. Here is the [update](https://github.com/tokamak-network/gem-nft-contract/blob/335c5599153893d72fa2504704876aa20e1a8d9b/src/L2/GemFactoryStorage.sol#L15)

**Comment by Zena-park** [comment]
I confirmed. Thank you.
