### ISSUE TITLE
[Code review: Contract Bugs]: (Question) Information stored in 'tokenURL' page

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#41]
### Describe the bug

 
 [Description](https://github.com/tokamak-network/gem-nft-contract?tab=readme-ov-file#description)
![스크린샷 2024-09-29 오후 5 27 23](https://github.com/user-attachments/assets/5bec697b-f958-4f08-ae3d-60cbd7109bf0)
 
 If tokenURL is an IPFS address as described in the description, **what information is shown in this tokenURL data on IPFS?**

In general, data uploaded to IPFS cannot be edited, so **I am curious about what information IPFS contains when the token specification has not been released yet.**

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/GemFactory.sol#L347-L352

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/GemFactory.sol#L473-L478

**Comment by 0x6e616d** [comment]
The token URI is used to store the token URI metadata (usually stored on IPFS), which includes NFT metadata such as attributes (traits and values) or the image URL of the NFT.

For example:

```json
{
  "image": "ipfs://.....",
  "attributes": [
    {
      "trait_type": "Background",
      "value": "Black"
    }
```

**Comment by mehdi-defiesta** [comment]
@0x6e616d Thank you. Indeed, I was thinking about storing the token URI within a second transaction after creating the NFT when the IPFS url is created.

**Comment by jusdy** [comment]
So as far as i understand, if we decided to save the metadata on ipfs, then first of all we should upload the metadata file with the corresponding metadata details (in our case, quadrants, color, etc) before we mint the NFT and we get the URI of that metadata file. (this would be done on FE side)
Then we will set that URI in the contract within the same transaction of creating GEM (like we've currently done).
Actually I don't think we need second transaction to store the URI specifically.

**Comment by Zena-park** [comment]
When requesting token generation, the token information is already embedded in the URL.
I understand. Thank you for your reply.
