### ISSUE TITLE
[Code review: Contract Bugs]: Recommend upgradeable treasury

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#42]
### Describe the bug

Since the Treasury holds TON/WSTON tokens in reserve, it is safer to use them as a proxy just in case.
Currently, the Treasury is a contract that cannot be upgraded.
It cannot prepare for future additions and changes to the logic.
 

### Recommendation

Please convert the Treasury to an upgradeable contract.

**Comment by mehdi-defiesta** [comment]
Thanks @Zena-park . Here is the code [update](https://github.com/tokamak-network/gem-nft-contract/commit/6df7365921e853dfbfda053d42508c0a13692155).

**Comment by Zena-park** [comment]
Could you please modify your test code to use a proxy? I would like to verify this through testing.

**Comment by mehdi-defiesta** [comment]
fixed in the following [commit](https://github.com/tokamak-network/gem-nft-contract/commit/3c3fae24298b2b419785401817f239bbf10e284d). Testing made appropriately (check [here](https://github.com/tokamak-network/gem-nft-contract/blob/3c3fae24298b2b419785401817f239bbf10e284d/test/L2/L2BaseTest.sol#L136-L144))

**Comment by Zena-park** [comment]
Please add code to check each setting value to making sure the entered value is set correctly in the test code after initializing?

**Comment by mehdi-defiesta** [comment]
@Zena-park  please check [this test suite](https://github.com/tokamak-network/gem-nft-contract/blob/codeRelease_apply/test/L2/L2Proxies.t.sol) for L2 proxies and [this one](https://github.com/tokamak-network/gem-nft-contract/blob/codeRelease_apply/test/L1/L1Proxies.t.sol) for L1 proxies
