### ISSUE TITLE
[Code review: Contract Bugs]: Duplicate code can be reused using modifier or function

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#43]
### Describe the bug

- The same code is used in multiple places.
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L90-L92
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L97-L99
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L104-L106
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L111-L113
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L118-L120
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L125-L127
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L133-L135
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L140-L142
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L147-L149
   https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L162-L164
    https://github.com/tokamak-network/gem-nft-contract/blob/a47ef0b91cb5d1ab3c19149619d3e1b8c9995225/src/L2/Treasury.sol#L175-L177
    
    

### Impact

It can reduce the code byte size.

It makes code management easier.

### Recommendation

  Replace duplicate above code with _checkNonAddress functions.
  
  ```
  function _checkNonAddress(address account) internal  {
          if(account == address(0))   revert InvalidAddress();
   }
   ```

**Comment by mehdi-defiesta** [comment]
@Zena-park Thank you. Here is the [update](https://github.com/tokamak-network/gem-nft-contract/blob/039a8c628cb60b238bea7f1d34a349d644585d70/src/L2/Treasury.sol#L243).

**Comment by Zena-park** [comment]
I confirmed. Thank you.

**Comment by Zena-park** [comment]
The parameter address is incorrect.
https://github.com/tokamak-network/gem-nft-contract/blob/039a8c628cb60b238bea7f1d34a349d644585d70/src/L2/Treasury.sol#L126
```
_checkNonAddress(ton); 
```

**Comment by mehdi-defiesta** [comment]
fixed in the following [commit](https://github.com/tokamak-network/gem-nft-contract/commit/3c3fae24298b2b419785401817f239bbf10e284d).

**Comment by Zena-park** [comment]
I confirmed. Thank you.
