### ISSUE TITLE
[Code review: Contract Bugs]: (Question) What are the L2 specs? 

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#44]
### Describe the bug

I thought L2 was tokamak-thanos. I think I was mistaken.
Treasury's ton is ERC20, not the native token. 
This contract doesn't support Thanos. 
Am I understanding this correctly? 

https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/Treasury.sol#L110-L113

**Comment by Zena-park** [comment]
@mehdi-defiesta The tests in [the documentation](https://github.com/tokamak-network/gem-nft-contract/blob/codeReview/README.md#contract-addresses) confirm that it is titan. 

If it's not a supported contract in Thanos, I think I can close this issue. 

I'll close it after your confirmation.

**Comment by mehdi-defiesta** [comment]
@Zena-park Yes, This contract was intended to be deployed on Titan only. However this is still under discussion. Can you send me a link showing how ton transfers are made on Thanos ?

**Comment by Zena-park** [comment]
In Titan, we use TON as a native token.
Think of it as Ether in L1.

(1) Simple example1.
```
(bool success, ) = payable(to).call{value: amount}("");
if (!success) revert NativeTokenTransferError();
```

(2) Example2 used in Titan,
https://github.com/tokamak-network/tokamak-thanos/blob/5ad9baac98217a0c1533969b00076d9a4443edba/packages/tokamak/contracts-bedrock/src/L2/L2StandardBridge.sol#L109-L110

**Comment by Zena-park** [comment]
This contract was intended to be deployed on Titan only. so I will close this issue.
