### ISSUE TITLE
[Code review: Contract Bugs]: Incorrect token contract when claiming withdrawal tokens

### ISSUE THREAD

**Issue by nguyenzung** [tokamak-network/gem-nft-contract#47]
### Describe the bug

I think we should use TON this case

[Describe the bug and its behavior! You can reference the problematic code using links (codeReview branch)](https://github.com/tokamak-network/gem-nft-contract/blob/2540ee12b1b81fd86ed77fb42daafb4bae864a64/src/L1/L1WrappedStakedTON.sol#L324)

### Impact

Users lose their tokens

**Comment by mehdi-defiesta** [comment]
Thanks @nguyenzung . You are not reviewing the right commit. Please use this [one](https://github.com/tokamak-network/gem-nft-contract/tree/codeReview). The current implementation you highlighted is still not definitive (initiated following @Zena-park 's [issue](https://github.com/tokamak-network/gem-nft-contract/issues/33)).

**Comment by nguyenzung** [comment]
I see, Thank you very much @mehdi-defiesta :heart:
