### ISSUE TITLE
[Code review: Contract Bugs]: Remove duplicate code

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#49]
### Describe the bug

Delete the code below. 
It is already included in the _putGemForSale function. 

https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/MarketPlace.sol#L100

### Impact

It reduces the gas costs.  

### Recommendation

Delete the code below. 
https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/MarketPlace.sol#L100

**Comment by mehdi-defiesta** [comment]
@Zena-park I don't see where it is included in `_putGemForSale`

**Comment by Zena-park** [comment]
Oops. My mistake.

I misunderstood the public function as an internal function.

You did it right.

Thank you for letting me know.
