### ISSUE TITLE
[Code review: Contract Bugs]: Exception handling when seller and buyer are the same 

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#50]
### Describe the bug

When seller and buyer are the same, if the transaction is executed, unnecessary gas is wasted.

https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/MarketPlace.sol#L167

### Impact

It can reduce gas.
Or it can perform functions that the owner really wants.

### Recommendation

When a seller and a payer are the same, It is recommended 
-   execute the removeGemForSale(uint256 _tokenId) function  
-  or handle a transaction failure.

**Comment by mehdi-defiesta** [comment]
fixed in the following [commit](https://github.com/tokamak-network/gem-nft-contract/commit/3c3fae24298b2b419785401817f239bbf10e284d)

**Comment by Zena-park** [comment]
I confirmed. Thank you.
