### ISSUE TITLE
[Code review: Contract Bugs]: Recommend to require the exact amount of Ether randomPackFees.

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#51]
### Describe the bug

  If a user accidentally pays too much Ether, will the transaction fail?

 - RandomPack is using ETH as a fee in IDRBCoordinator but it is not checking how much he needs to receive. 
 
https://github.com/tokamak-network/gem-nft-contract/blob/b31e833a38901bee6287b869d34c523bfe13dea2/src/L2/Randomness/DRBConsumerBase.sol#L34-L36
 

### Recommendation

If you are already receiving fees in TON, and additionally receiving fees in ETH, a more clear implementation is needed.

**Comment by mehdi-defiesta** [comment]
@Zena-park the coordinator has the following parameters:
```Solidity
//DRB storage
uint256 public avgL2GasUsed = 2100000;
uint256 public premiumPercentage = 0;
uint256 public flatFee = 0.001 ether;
uint256 public calldataSizeBytes = 2071;
```
the average L2 gas spent is going to indicate the amount of ETH to be used. 
Anyway, my opinion is that we should let the UI define the amount of ETH to send.

**Comment by Zena-park** [comment]
@usgeeus
 I have a question. When using i_drbCoordinator.requestRandomWordDirectFunding, what happens if too much ether is sent?

**Comment by usgeeus** [comment]
Then the users just lose money. We can modify the DRBConsumerBase like this 
```
    /**
     * @return requestId The ID of the request
     * @dev Request Randomness to the Coordinator
     */
    function requestRandomness(uint16 security, uint16 mode, uint32 callbackGasLimit) internal returns (uint256) {
        uint256 directFundingPrice = i_drbCoordinator.calculateDirectFundingPrice(
            IDRBCoordinator.RandomWordsRequest({security: security, mode: mode, callbackGasLimit: callbackGasLimit})
        );
        uint256 requestId = i_drbCoordinator.requestRandomWordDirectFunding{value: directFundingPrice}(
            IDRBCoordinator.RandomWordsRequest({security: security, mode: mode, callbackGasLimit: callbackGasLimit})
        );
        return requestId;
    }
```
This modification would leave the remaining excess ETH in the RandomPack contract, then the logic for that would need to be implemented in RandomPack.

**Comment by Zena-park** [comment]
@usgeeus  Thanks for the answer.

@mehdi-defiesta  Since the excess amount is left in the contract, I think the remaining ether should be returned to the user,
or only the amount needed should be received from the beginning.

**Comment by usgeeus** [comment]
We can't guarantee that only the amount needed to be received from the beginning, because the request cost depends on the gasprice. It depends on the nature of the network, especially on networks with fluctuating gas prices, it cannot be guaranteed.
So please develop the logic that returns the remaining ETH to the user.

**Comment by mehdi-defiesta** [comment]
thanks @usgeeus for the clarification

**Comment by mehdi-defiesta** [comment]
Ethers are sent to the DRBCoordinator contract through the `requestRandomWordDirectFunding` function. I think the coordinator has to return the remaining ETH and this can only be done through the DRBCoordinator contract. One alternative is to call the `estimateDirectFundingPrice` and enforce the user to send msg.value = X + delta (to avoid discrepancy between the time the randomness is requested and the time the FulfillRandomness is done). 
What do you think @usgeeus about this last solution ?

**Comment by usgeeus** [comment]
Brief overview of directFunding

request cost = gas cost to generate random number + node incentive
The gas cost to generate a random number is calculated as gasprice * gasUsed. We fixed gasUsed to a constant by finding a value in advance.

Initially, we considered two mechanisms: subscription and directFunding. However, the subscription method requires consumers to deposit ETH in advance, which is inconvenient, so we developed only with directFunding.

Subscription allowed to accurately calculate the request cost with the actual gasprice value at the time of `request` and `fulfillRandomness` tx.
However, directFunding mechanism calculates the request cost based on the gas price at the time of `request` and receives it from the user. Therefore, the profit and loss of nodes at the `FulfillRandomness` tx depends on the gas price at that time. (Chainlink, there is overhead for directFunding cost to account for possible losses)

----------------------------

Issue with directFunding

The problem is that gasprice * gasUsed is pre-calculated off-chain (estimateDirectFundingPrice) and the transaction is sent with the value set, but by the time the transaction is confirmed (calculateDirectFundingPrice), the gasprice may be different.
For reference, according to EIP 1559 on the Ethereum mainnet, the maximum increase or decrease in the base fee from the previous block is 12.5%.
So if you multiply the current gasprice by 112.5% off-chain and set the value via estimateDirectFundingPrice, you can run the request function safely on Ethereum mainnet.

There are several options for what to do with the excess ETH.
1. DRBCoordinator does not refund the excess value. (Currently our and Chainlink's version)
This case can also be broken down into two parts.
    1.1. Send the exact requestCost to DRBCoordinator via the calculateDirectFundingPrice function in the ConsumerBase contract (the contract you need to inherit when developing the Consumer contract) and let the Consumer developer  implement additional logic for what to do with remaining ETH. e.g. return the remaining ETH to the user. (Current Chainlink's version and the comment that I suggested(https://github.com/tokamak-network/gem-nft-contract/issues/51#issuecomment-2392627564). 
    1.2. Just send the excess ETH to the DRBCoordinator.

2. DRBCoordinator refunds the excess value.
In this case, the implementation of the receive function in the Consumer is mandatory, which can be enforced by declaring the receive function of the abstract contract ConsumerBase as virtual and empty, and the Consumer developer should override the receive function to implement additional logic for the refunded ETH. e.g. return the refunded ETH to the user.

Both 1.1 and 2 are the same in that the consumer developer has to write additional logic and users can pay the exact requestCost. However, the additional logic also costs gas, which can be a bit of an inefficient model if the gas cost for the additional logic is more than the ETH refunded.
However, in 1.2, there is no additional logic, so the gas cost for request transactions is relatively low.

I'll think about this a bit and come back with additional comment. @mehdi-defiesta @shlee-lab

**Comment by usgeeus** [comment]
@mehdi-defiesta 

Let's go with method 1.1. This is the method that [chainlink](https://github.com/smartcontractkit/chainlink/blob/1b41e69cca2f4622d367ef18733c36fcae433505/contracts/src/v0.8/vrf/dev/VRFV2PlusWrapperConsumerBase.sol#L82-L92) also uses. You can modify it with what I left in the comments here (https://github.com/tokamak-network/gem-nft-contract/issues/51#issuecomment-2392627564).

This prevents DRBCoordinator from having to refund.

So implement the logic for what to do with the remaining ETH in the requestRandomGem function of the RandomPack which is the consumer contract.

**Comment by usgeeus** [comment]
I suggest improvements.

**ConsumerBase.sol**
```
/**
     * @return requestId The ID of the request
     * @dev Request Randomness to the Coordinator
     */
    function requestRandomness(uint16 security, uint16 mode, uint32 callbackGasLimit) internal returns (uint256 directFundingCost, requestId) {
       directFundingCost = i_drbCoordinator.calculateDirectFundingPrice(
            IDRBCoordinator.RandomWordsRequest({security: security, mode: mode, callbackGasLimit: callbackGasLimit})
        );
       requestId = i_drbCoordinator.requestRandomWordDirectFunding{value: directFundingPrice}(
            IDRBCoordinator.RandomWordsRequest({security: security, mode: mode, callbackGasLimit: callbackGasLimit})
        );
    }
```
   
   **RandomPack.sol**
```
/**
 * @notice Requests a random GEM and pays the required fees.
 * @return uint256 Returns the request ID for the randomness request.
 * @dev function has nonReentrant modifier and follows CEI
 */
function requestRandomGem() external payable whenNotPaused nonReentrant returns(uint256) {
    if(msg.sender == address(0)) {
        revert InvalidAddress();
    }
    //users pays upfront fees
    //user must approve the contract for the fees amount before calling the function
    IERC20(ton).safeTransferFrom(msg.sender, address(this), randomPackFees);
    
    // defining the random value
    (uint256 directFundingCost, uint256 requestId) = requestRandomness(0,0,callbackGasLimit);        

    s_requests[requestId].requested = true;
    s_requests[requestId].requester = msg.sender;
    unchecked {
        requestCount++;
    }

    if(msg.value > directFundingCost) { // if there is ETH to refund
        (bool success, ) = msg.sender.call{value:  msg.value - directFundingCost}("");
        if(!success) {
            revert FailedToSendEthBack();
        }
    }

    emit RandomGemRequested(msg.sender);
    return requestId;
}
```

**Comment by Zena-park** [comment]
If the amount of ether is less than directFundingPrice, transaction should be reverted.

```
function requestRandomGem() external payable whenNotPaused nonReentrant returns(uint256) {
    if(msg.sender == address(0)) {
        revert InvalidAddress();
    } 
     uint256 directFundingPrice = i_drbCoordinator.calculateDirectFundingPrice(
        IDRBCoordinator.RandomWordsRequest({security: 0, mode: 0, callbackGasLimit: callbackGasLimit})
    );
    
    if(msg.value < directFundingPrice) revert DirectFundingPriceError();
    
    //users pays upfront fees
    //user must approve the contract for the fees amount before calling the function
    IERC20(ton).safeTransferFrom(msg.sender, address(this), randomPackFees);
    
    // defining the random value
    uint256 requestId = requestRandomness(0,0,callbackGasLimit);        

    s_requests[requestId].requested = true;
    s_requests[requestId].requester = msg.sender;
    unchecked {
        requestCount++;
    }

    // return back the excess ETH to msg.sender (if any) 
    if(msg.value - directFundingPrice != 0) { // if there is ETH to refund
        uint256 excessEth = msg.value - directFundingPrice;
        (bool success, ) = msg.sender.call{value: excessEth}("");
        if(!success) {
            revert FailedToSendEthBack();
        }
    }

    emit RandomGemRequested(msg.sender);
    return requestId;
}
```

**Comment by usgeeus** [comment]
@Zena-park It will revert in DRBCoordinator contract anyway if the amount of ether is less than directFundingPrice.
Therefore, I don't recommend adding that require statement to save gas.
@mehdi-defiesta

**Comment by Zena-park** [comment]
@usgeeus I got it, thanks for letting me know.

@mehdi-defiesta I think it would be better to use the code @usgeeus gave you.

**Comment by usgeeus** [comment]
Here is one more suggestion for improvement

1. try to get the gasused of only the following logic by testing, you should only measure for this line of code.
```
(bool success, ) = msg.sender.call{value: msg.value - directFundingPrice}("");
if(!success) {
    revert FailedToSendEthBack();
}
 ```
 2. Declare the value you got in step 1 as a constant in your contract. 
 ```
 uint256 constant private GASUSED_SENDETH = 
 ```
 
 3.  modify the if statement
 ```
 if(msg.value > directFundingCost + (GASUSED_SENDETH * tx.gasprice)) { // if there is ETH to refund 
        (bool success, ) = msg.sender.call{value:  msg.value - directFundingCost}("");
        if(!success) {
            revert FailedToSendEthBack();
        }
    }
 ```
 
 If you think `+ (GASUSED_SENDETH * tx.gasprice)` is a waste of gas, feel free to ignore this suggestion.
 I'm not sure this is a good idea right now, but please give it some thought and consideration.
 
 @mehdi-defiesta @Zena-park

**Comment by mehdi-defiesta** [comment]
@usgeeus @Zena-park Thank you for your help. I have [tested](https://github.com/tokamak-network/gem-nft-contract/blob/ffbbbf810bee2b9435b0ea09dc8dc9a0f6dcfaeb/test/L2/RandomPack.t.sol#L61-L83) the update and it seems to work properly. Here is the test I have made:
```Solidity
/**
 * @notice testing the getRandomGem function 
 * @dev we created 2 gems (one RARE and one UNIQUE) that are eligible for being picked by the node
 * @dev called requestRandomGem with msg.value = 0.005 ETH (price of requesting is equal to 0.001 ETH)
 * @dev expected the EthSentBack event is triggered with the appropriate amount
 * @dev simulated the node calling fulfillRandomness and ensured the GEM is appropriately picked and transferred
 */
function testGetRandomGem() public {

    // create a pool of premined gem
    vm.startPrank(owner);

    // Define GEM properties
    uint8[2][] memory colors = new uint8[2][](2);
    colors[0] = [0,0];
    colors[1] = [1,1];

    GemFactoryStorage.Rarity[] memory rarities = new GemFactoryStorage.Rarity[](2);
    rarities[0] = GemFactoryStorage.Rarity.RARE;
    rarities[1] = GemFactoryStorage.Rarity.UNIQUE;
    
    uint8[4][] memory quadrants = new uint8[4][](2);
    quadrants[0] = [2, 3, 3, 2];
    quadrants[1] = [4, 3, 4, 3];

    string[] memory tokenURIs = new string[](2);
    tokenURIs[0] = "https://example.com/token/1";
    tokenURIs[1] = "https://example.com/token/2";

    // Call createPreminedGEMPool function from the Treasury contract
    uint256[] memory newGemIds = Treasury(treasuryProxyAddress).createPreminedGEMPool(
        rarities,
        colors,
        quadrants,
        tokenURIs
    );

    // Verify GEM creation
    assert(newGemIds.length == 2);
    assert(GemFactory(gemfactoryProxyAddress).ownerOf(newGemIds[0]) == treasuryProxyAddress);
    assert(GemFactory(gemfactoryProxyAddress).ownerOf(newGemIds[1]) == treasuryProxyAddress);
    assert(keccak256(abi.encodePacked(GemFactory(gemfactoryProxyAddress).tokenURI(newGemIds[0]))) == keccak256(abi.encodePacked(tokenURIs[0])));
    assert(keccak256(abi.encodePacked(GemFactory(gemfactoryProxyAddress).tokenURI(newGemIds[1]))) == keccak256(abi.encodePacked(tokenURIs[1])));

    vm.stopPrank();

    vm.startPrank(user1);
    // calculate the price of funding the DRBCoordinator
    uint32 callbackGasLimit = 600000;
    uint256 directFundingCost = drbCoordinatorMock.calculateDirectFundingPrice(
        IDRBCoordinator.RandomWordsRequest({security: 0, mode: 0, callbackGasLimit: callbackGasLimit})
    );
    // approving the randomPack contract to transfer the fees from the user to the contract
    MockTON(ton).approve(randomPackProxyAddress, randomPackFees);

    // Calculate the expected amount to be sent back for the event
    uint256 expectedAmount = randomBeaconFees - directFundingCost;

    // Capture the event
    vm.expectEmit(true, true, true, true);
    emit RandomPackStorage.EthSentBack(expectedAmount);
    // call requestRandomGem by sending msg.value = 0.005 ETH
    uint256 requestId = RandomPack(randomPackProxyAddress).requestRandomGem{value: randomBeaconFees}();
    // simulated the node calling fulfillRandomness
    drbCoordinatorMock.fulfillRandomness(requestId);
    // ensuring the either one of the minted GEM is transferred to user 1
    assert(GemFactory(gemfactoryProxyAddress).ownerOf(newGemIds[0]) == user1 || GemFactory(gemfactoryProxyAddress).ownerOf(newGemIds[1]) == user1);

    vm.stopPrank();
}
```

**Comment by usgeeus** [comment]
@mehdi-defiesta 
cache to stack to save gas.

https://github.com/tokamak-network/gem-nft-contract/blob/ffbbbf810bee2b9435b0ea09dc8dc9a0f6dcfaeb/src/L2/RandomPack.sol#L156-L161

```
            uint256 ethToRefund = msg.value - directFundingCost;
            (bool success, ) = msg.sender.call{value:  ethToRefund}("");
            if(!success) {
                revert FailedToSendEthBack();
            }
            emit EthSentBack(ethToRefund);
```

**Comment by mehdi-defiesta** [comment]
@usgeeus thank you every insights were considered in the last [commit](https://github.com/tokamak-network/gem-nft-contract/tree/codeReview2)
