### ISSUE TITLE
[Code review: Contract Bugs]: (Question) Isn't it possible to do ZERO randomPackFees?

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#52]
### Describe the bug

Is there no possibility of setting randomPackFees to 0?

Initial events and marketing, etc. 
Since it's a policy decision, shouldn't we consider of a possibility?

**Comment by mehdi-defiesta** [comment]
This is never going to be 0 since it would act as an arbitrage opportunity where users can drain the entire pool of Gems for free. In that case we would use the airdrop contract instead. We estimated the price of running the function at around 20 TON and this should not be changed over time.

**Comment by Zena-park** [comment]
Understood, thank you.
