### ISSUE TITLE
[Code review: Contract Bugs]: Unable to view storage value

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#54]
### Describe the bug

There is no view function that can check the values ​​of _marketplace, airdrop, wston, ton, and wstonSwapPool. 

https://github.com/tokamak-network/gem-nft-contract/blob/039a8c628cb60b238bea7f1d34a349d644585d70/src/L2/Treasury.sol#L28-L34

### Impact

You should be able to check the settings value.

### Recommendation

Please change the values ​​of _marketplace, airdrop, wston, ton, and wstonSwapPool to 'public' or add a view function.

**Comment by mehdi-defiesta** [comment]
fixed in the following [commit](https://github.com/tokamak-network/gem-nft-contract/commit/3c3fae24298b2b419785401817f239bbf10e284d)

**Comment by Zena-park** [comment]
I confirmed. Thank you.
