### ISSUE TITLE
[Code review: Contract Bugs]: Recommended to inherit ERC721Enumerable.

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#56]
### Describe the bug

It is recommended that the following functions for cost a lot of gas, inherit [ERC721Enumerable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721Enumerable.sol).

https://github.com/tokamak-network/gem-nft-contract/blob/039a8c628cb60b238bea7f1d34a349d644585d70/src/L2/GemFactory.sol#L818-L847

### Impact

Gas fee can be reduced.

### Recommendation

I haven't tested it. I'm just giving you a guide.

```
function tokensOfOwner(address _owner) public view returns (uint256[] memory ownerTokens) {
        uint256 tokenCount = balanceOf(_owner);

        if (tokenCount == 0) {
            // Return an empty array
            return new uint256[](0);
        } else {
            uint256[] memory result = new uint256[](tokenCount);
            unit256 i;
            for ( i; i < tokenCount; i++) {
               result[i] = tokenOfOwnerByIndex(_owner, i)
            } 
            return result;
       }
    }
```

**Comment by mehdi-defiesta** [comment]
The problem is that I already import ERC721Storage which inherits from ERC721. I cannot import both ERC721Storage and ERC721Enumerable. Since this contract is going to be deployed on L2 only, I don't think it is worth importing new storage to spend less gas.

**Comment by mehdi-defiesta** [comment]
@Zena-park

**Comment by Zena-park** [comment]
Okay. I will close this issue.
