### ISSUE TITLE
[Code review: Contract Bugs]: Duplicate code within a transferFrom function

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#57]
### Describe the bug

 
 Lines 562-563 are codes that exist within the [super.transferFrom(from, to, tokenId);](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/49cd64565aafa5b8f6863bf60a30ef015861614c/contracts/token/ERC721/ERC721.sol#L138-L140) function.
 ```
     if(to == address(0)) { 
         revert AddressZero(); 
     } 
 ```    
 https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/GemFactory.sol#L560-L576
 
 

### Recommendation

```
function transferFrom(address from, address to, uint256 tokenId) public override(ERC721, IERC721) whenNotPaused {
        
        if(to == from) {
            revert SameSenderAndRecipient();
        }
        if(Gems[tokenId].isLocked) {
            revert GemIsLocked();
        }
        super.transferFrom(from, to, tokenId);
        Gems.transferGem(GEMIndexToOwner, ownershipTokenCount, from, to, tokenId);
        
        emit TransferGEM(from, to, tokenId);
    }

```

**Comment by mehdi-defiesta** [comment]
fixed in the following [commit](https://github.com/tokamak-network/gem-nft-contract/commit/3c3fae24298b2b419785401817f239bbf10e284d)

**Comment by Zena-park** [comment]
I confirmed. Thank you.
