### ISSUE TITLE
[Code review: Contract Bugs]: The '_distributeFees' function's gas fees issue

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#60]
### Describe the bug

The swapWSTONforTON function's gas fees will continue to increase as the number of lpAddresses increases.
It seems unreasonable to make the user pay the gas fee for the fee distribution to lpAddresses. 
 
https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/WstonSwapPool.sol#L104

https://github.com/tokamak-network/gem-nft-contract/blob/306b8fd7de7163e11cfcef0ec7c1dd7e12f6f088/src/L2/WstonSwapPool.sol#L159-L179

### Recommendation

The fee distribution to lpAddresses should be run when lpAddresses are changed, or let them run and pay the gas fee themselves.

**Comment by mehdi-defiesta** [comment]
Thanks @Zena-park . I implemented a **Pull Over Push Model**:
Instead of distributing fees immediately during the swap, we accumulate the fees in a pool and allow liquidity providers to claim their share of the fees at their convenience. This shifts the gas cost to the liquidity providers who can decide when to claim their rewards. Here is the code [update](url)

I have created the following storage:
```Solidity
uint256 public tonFeeBalance;
uint256 public wstonFeeBalance;
```
Then I have created the `claimFees` function:
```Solidity
 /**
 * @notice Distributes accumulated TON and WSTON fees to liquidity providers based on their share.
 * @dev This function iterates over all liquidity providers and distributes fees proportionally.
 *      It resets the fee balances before distribution to prevent reentrancy attacks.
 *      Ensure that the function is called when there are fees to distribute to avoid unnecessary gas costs.
 * @dev Emits a {FeesDistributed} event.
 * @dev Uses the nonReentrant modifier to prevent reentrancy attacks.
 */
function distributeFees() external nonReentrant {
    uint256 tonFees = tonFeeBalance;
    uint256 wstonFees = wstonFeeBalance;
    require(tonFees > 0 || wstonFees > 0, "No fees to claim");

    // reset storage variables before transferring
    tonFeeBalance = 0;
    wstonFeeBalance = 0;

    if (totalShares == 0) return;

    for (uint256 i = 0; i < lpAddresses.length; ++i) {
        address lp = lpAddresses[i];
        uint256 share = lpShares[lp];
        if (share > 0) {
            uint256 tonReward = (tonFees * share) / totalShares;
            uint256 wstonReward = (wstonFees * share) / totalShares;

            if (tonReward > 0) {
                _safeTransfer(IERC20(ton), lp, tonReward);
            }
            if (wstonReward > 0) {
                _safeTransfer(IERC20(wston), lp, wstonReward);
            }
        }
    }

    emit FeesDistributed(tonFees, wstonFees);
}
```

Finally I have updated `swapWSTONtoTON` and `swapTONforWSTON` function by replacing
```Solidity
_distributeFees(0, fee);
```
to
```Solidity
tonFeeBalance += fee;
```
and
```Solidity
_distributeFees(fee, 0);
```
to
```Solidity
wstonFeeBalance += fee;
```

**Comment by mehdi-defiesta** [comment]
code [update](https://github.com/tokamak-network/gem-nft-contract/blob/1f16b62589a5d302e29f39ff319cee831a4167b9/src/L2/WstonSwapPool.sol#L146-L182)

**Comment by mehdi-defiesta** [comment]
Actually the contract is still vulnerable to DoS with an attacker depositing a small amount thousands of time to fill in the lpAddresses array until LPs can't collect fees anymore. I will implement a new way of managing address duplicates in addLiquidity/removeLiquidty functions

**Comment by Zena-park** [comment]
I confirmed. Thank you.
