### ISSUE TITLE
Update the Created event with the miningTry value

### ISSUE THREAD

**Issue by jusdy** [tokamak-network/gem-nft-contract#70]
event Created(
        uint256 indexed tokenId, 
        Rarity rarity, 
        uint8[2] color, 
        uint256 value,
        uint8[4] quadrants, 
        uint32 miningPeriod,
        uint256 cooldownDueDate,
        string tokenURI, 
        address owner
    );

we should need to add the miningTry value on this event.

**Comment by mehdi-defiesta** [comment]
@jusdy fixed in this [commit](https://github.com/tokamak-network/gem-nft-contract/commit/56baaa0f16c824dc209079207457696f83c69a2e)
