### ISSUE TITLE
Wrong assigned CooldownDueDate value on forgeToken function

### ISSUE THREAD

**Issue by jusdy** [tokamak-network/gem-nft-contract#72]
https://github.com/tokamak-network/gem-nft-contract/blob/154a7bfbdb04dfa7f85c05e90646ec193062c6fb/src/L2/GemFactoryForging.sol#L98

here, it's currently assigning **cooldownPeriod** value, I think it should be **cooldownDueDate** value with calculating **block.timestamp + cooldownPeriod**

**Comment by mehdi-defiesta** [comment]
@jusdy fixed in this [commit](https://github.com/tokamak-network/gem-nft-contract/commit/56baaa0f16c824dc209079207457696f83c69a2e)
