### ISSUE TITLE
[Code review: Contract Bugs]: Inconsistency logic when handling TON and WTON

### ISSUE THREAD

**Issue by nguyenzung** [tokamak-network/gem-nft-contract#75]
### Describe the bug

Both deposit and withdrawal process allow using TON and WTON without any checking.
=> It can lead to a case such that, There are total 10 TON and 10 WTON in the deposit process, however there are 20 WTON in the withdrawal process 

### Impact

It could lead to case that some users can not withdraw token they want. 

### Recommendation

- If userA deposits 10 TON and 10 WTON, they will be able to withdraw 10TON and 10WTON. 
- Considering support only 1 token for the core logic. With this approach, other token can be handled by swapping to the supported token first

**Comment by mehdi-defiesta** [comment]
Thanks @nguyenzung. The issue you describe is intended. The L1WrappedStakedTON contract does not act as a Treasury and does not hold any WTON/TON. Every tokens are sent to the deposit manager. As for the withdraw, it is the same: we receive tokens from the deposit manager. Therefore, we can let user choose to withdraw either in TON or WTON eventhough they deposited using a single type of token.
