### ISSUE TITLE
[Code review: Contract Bugs]: Users cannot claim withdrawal in some cases when DepositManager processRequest from lowIndex to highIndex

### ISSUE THREAD

**Issue by nguyenzung** [tokamak-network/gem-nft-contract#76]
### Describe the bug

Let say there are 2 users A and B. A withdrawal can not be claimed in scenario below
- A deposit 1 WTON
- A requestWithdrawal 1 WTON
- B deposit 1000 WTON
- B requestWithdrawal 1000WTON
- B claimWithdrawal: failed

Reason: https://github.com/tokamak-network/gem-nft-contract/blob/codeReview2/src/L1/L1WrappedStakedTON.sol#L469
DepositManager processes withdrawal without any knowledge about the order of withdrawals. In this scenario, there are 2 withdrawal request in order A's request ->B's request. 

DepositManager will try to process the request of A first.  DepositManager send 1WTON to the L1WrappedStakedTON however it is not enough for B to claim => tx reverts

### Impact

claimWithdrawal can be disable for some users temporary

**Comment by mehdi-defiesta** [comment]
Thanks @nguyenzung I think you are right. The less liquidity, the more chance user would encounter this situation. What do you suggest to mitigate this risk ?

**Comment by mehdi-defiesta** [comment]
```Solidity
// Process request in TON or WTON
  if (_token) {
      // if there is enough funds in the contract, it means that someone else has already processRequest
      // this avoid the scenario where processRequest fails because it was already called preivously and no request can be processed anymore in the depositManager
      if(IERC20(ton).balanceOf(address(this)) >= totalClaimableAmount) {
          totalClaimableAmount = totalClaimableAmount / 10 ** 9;
          IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
      } else{
          if (!IDepositManager(depositManager).processRequest(layer2Address, true)) {
              revert ProcessRequestFailed();
          }
          totalClaimableAmount = totalClaimableAmount / 10 ** 9;
          IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
      }
  } else {
      if(IERC20(wton).balanceOf(address(this)) >= totalClaimableAmount) {
          IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
      } else{
          if (!IDepositManager(depositManager).processRequest(layer2Address, false)) {
              revert ProcessRequestFailed();
          }
          IERC20(wton).safeTransfer(msg.sender, totalClaimableAmount);
      }
  }
```

can you confirm this would fix the issue ?

**Comment by mehdi-defiesta** [comment]
@nguyenzung There is no orders of processWithdrawal in DepositManager. Once we call `processRequest()` we receive he accumulated amount of unclaimed requests. for example:
- user A deposits 100 WTON
- user A requestWithdrawal for 50 WTON
- user A requestWithdrawal for 50 WTON again
- user A calls `processRequest()`
- user A receives 100 WTON

Likewise in claimWithdrawal, if a user calls the function, it will call `processRequest()`and trigger a transfer of all requests made by users. The contract will hold the total claimable amount and that's why we implemented the condition indicating that if the contracts holds enough funds to cover the user's request, we don't call processRequest as it will automatically revert.

Here is the workflow from our contract point of view:
- user A deposits 100 WTON for 100 WSTON
- user B deposits 5O WTON for 50 WSTON
- user A request withdrawal for 100 WSTON
- user B request withdrawal for 50 WSTON
After 1 month:
- user A calls claimWithdrawal => triggers `processRequest`and will send 150 WTON to L1WrappedStakedTON
- userA receives 100 WTON
- user B calls claimWithdrawal => since the contract still has 50 WTON it will directly transfer the amount to user B
- user B receives 50 WTON

**Comment by mehdi-defiesta** [comment]
@nguyenzung I see what you mean. I modified the function so it transfers the funds in TON only so there is no discrepancy between what was sent from the depositManager and what the user gets. Here is the [code update](https://github.com/tokamak-network/gem-nft-contract/blob/f8eccb96e04800210de4d7d4163fc335d10bd219/src/L1/L1WrappedStakedTON.sol#L416-L429).  
I've [tested](https://github.com/tokamak-network/gem-nft-contract/blob/f8eccb96e04800210de4d7d4163fc335d10bd219/test/L1/L1WrappedStakedTON.t.sol#L440-L479) the function with the scenario. you mentioned and it seems to work properly. Can you confirm ?

**Comment by mehdi-defiesta** [comment]
> As I checked, DepositManager prioritize ealier withdrawal
> 
> * Query index: https://github.com/tokamak-network/gem-nft-contract/blob/codeReview2/src/L1/Mock/DepositManager.sol#L267
> * Increase index: https://github.com/tokamak-network/gem-nft-contract/blob/codeReview2/src/L1/Mock/DepositManager.sol#L272
> 
> It makes a recored when receiving a requestWithdrawal: https://github.com/tokamak-network/gem-nft-contract/blob/codeReview2/src/L1/Mock/DepositManager.sol#L242
> 
> So in the example case, when B claimWithdrawal there are 100WTON sent to L1WrappedStakedTON

Regarding the depositManager, the last request is the sum of all unclaimed amounts. Therefore, by calling `_processRequest`, the user gets the entire balance of unclaimed amounts. That is why if a user calls `claimWithdrawal` in `L1WrappedStakedTON`, the depositManager is going to send all claimable funds related to all the requests made by the users => The if statement [here](https://github.com/tokamak-network/gem-nft-contract/blob/f8eccb96e04800210de4d7d4163fc335d10bd219/src/L1/L1WrappedStakedTON.sol#L465) will avoid the function reverting if someone has already called `claimWithdrawal`

**Comment by mehdi-defiesta** [comment]
@nguyenzung you are right let me fix that

**Comment by mehdi-defiesta** [comment]
@nguyenzung I fixed it like that :
```Solidity
totalClaimableAmount = totalClaimableAmount / 10 ** 9;
/// if there is enough funds in the contract, it means that someone else has already processRequest
/// this avoid the scenario where processRequest fails because it was already called previously 
/// and no request can be processed anymore in the depositManager
if(IERC20(ton).balanceOf(address(this)) >= totalClaimableAmount) {
    IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
} else{
    uint256 numPendingRequests = IDepositManager(depositManager).numPendingRequests(layer2Address, address(this));
    if(numPendingRequests > 0) {               
        if (!IDepositManager(depositManager).processRequests(layer2Address, numPendingRequests, true)) {
            revert ProcessRequestFailed();
        }
    }
    IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
}
```
I have updated claimWithdrawalTotal and claimWithdrawalIndex accordingly.
The tests passes now. Here is the commit [link](https://github.com/tokamak-network/gem-nft-contract/commit/3716aae311319ff4b98525d39c57dc1836cf792f)
Can you check and confirm ?

**Comment by nguyen-zung** [comment]
This solution can lead to the case that running out of gas  if numPendingRequests is big.

**Comment by mehdi-defiesta** [comment]
Indeed. Then what do you suggest ? I was thinking about implementing a minimum deposit/withdrawal amount

**Comment by mehdi-defiesta** [comment]
ok you are right it runs out of gas : 
```Solidity
/**
* @notice checking if claimWithdrawal does not run out of gas if there is a large amount of requests
*/
function testClaimWothdrawalCannotRunOutOfGas() public {
    // user1 deposit
    vm.startPrank(user1);
    uint256 depositAmount = 4000 * 10**27;
    WTON(wton).approve(address(l1wrappedstakedtonProxy), depositAmount);
    L1WrappedStakedTON(address(l1wrappedstakedtonProxy)).depositWTONAndGetWSTON(depositAmount, false);


    // move to the next 200000 block
    vm.roll(block.number + 200000);

    // requesting for 1 WEI
    for (uint i = 0; i < 4000; ++i) {
        L1WrappedStakedTON(address(l1wrappedstakedtonProxy)).requestWithdrawal(1e27);
    }

    // rolling up to 1 block before due date
    vm.roll(block.number + delay);
    // claim total to check if numPendingRequest does not make the function running out of gas
    L1WrappedStakedTON(address(l1wrappedstakedtonProxy)).claimWithdrawalTotal();

}
```

How can we avoid this ?

**Comment by mehdi-defiesta** [comment]
Making a minimum deposit amount/withdraw could resolve the issue

**Comment by mehdi-defiesta** [comment]
Maybe I should set a maximum withdrawal requests so that user must claim first to request again

**Comment by mehdi-defiesta** [comment]
@Zena-park can you give your thoughts on that?

**Comment by mehdi-defiesta** [comment]
If you don't find any solution, we will assume the only way is to restrict users to only withdraw their entire balance when they call `requestWithdrawal`

**Comment by Zena-park** [comment]
@mehdi-defiesta If you want to modify the TON Staking contract, you can upgrade the contract by submitting a TON Staking contract modification proposal (a transaction that changes the logic of the contract) to the Tokamak DAO, DAO members vote on a proposal, and executing the transaction.

**Comment by Zena-park** [comment]
It would be a good idea to create an additional function that only calls the IDepositManager(depositManager).processRequests(layer2Address, n, true) function so that the team can manage it before a problem occurs.

Suppose people know that the processRequests(layer2Address, n, true) function of the withdrawal processing process will process all the withdrawals of people who requested withdrawals before me, they can intentionally process the withdrawals late. If someone processes the processRequests that includes my withdrawal request, I can save on gas fees.
In this case, if no one processes the withdrawal, the number of withdrawals will continue to accumulate, and an extreme gas fee problem can occur.
The team should know the maximum number of withdrawals or the appropriate number of withdrawals to prevent this problem from occurring. If a withdrawal processing wait occurs that increases this number, you can prevent service failure by reducing the number of withdrawal processing requests n by simply calling the IDepositManager(depositManager).processRequests(layer2Address, n, true) function.

**Comment by Zena-park** [comment]
> @nguyenzung I fixed it like that :
> 
> ```solidity
> totalClaimableAmount = totalClaimableAmount / 10 ** 9;
> /// if there is enough funds in the contract, it means that someone else has already processRequest
> /// this avoid the scenario where processRequest fails because it was already called previously 
> /// and no request can be processed anymore in the depositManager
> if(IERC20(ton).balanceOf(address(this)) >= totalClaimableAmount) {
>     IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
> } else{
>     uint256 numPendingRequests = IDepositManager(depositManager).numPendingRequests(layer2Address, address(this));
>     if(numPendingRequests > 0) {               
>         if (!IDepositManager(depositManager).processRequests(layer2Address, numPendingRequests, true)) {
>             revert ProcessRequestFailed();
>         }
>     }
>     IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
> }
> ```
> 
> I have updated claimWithdrawalTotal and claimWithdrawalIndex accordingly. The tests passes now. Here is the commit [link](https://github.com/tokamak-network/gem-nft-contract/commit/3716aae311319ff4b98525d39c57dc1836cf792f) Can you check and confirm ?

The **numPendingRequests** function includes those that have not passed the deplay block,
so only pending requests whose withdrawableBlockNumber is smaller than the current block should be requested.
```

struct WithdrawalReqeust {
uint128 withdrawableBlockNumber;
uint128 amount;
bool processed;
}
```

**Comment by mehdi-defiesta** [comment]
I've made several updates : [commit](https://github.com/tokamak-network/gem-nft-contract/commit/1a477ac9fe0f93dc44d50f703b63843be09ae045) 

- users are getting TON only after processing the withdrawal (WTON withdrawal disabled).
- created a `numWithdrawableRequests`function to get the number of pending requests that are withdrawable

```Solidity
/**
* @notice calculating the number of withdrawal requests that can be processed 
* @dev we fetch the number of requests made by the contract, as well as the number of the last index
* @dev we iterrate over the number of pending requests and check if it is withdrawable 
* @return count the total number of withdrawable requests
*/
function numWithdrawableRequests() internal view returns (uint256) {
  uint256 numRequests = IDepositManager(depositManager).numRequests(layer2Address, address(this));
  uint256 index = IDepositManager(depositManager).withdrawalRequestIndex(layer2Address, address(this));
  uint256 count;

  if (numRequests == 0) return 0;
  uint256 numberPendingRequests = numRequests - index;

  for(uint256 i = 0; i < numberPendingRequests; ++i) {
      (uint128 withdrawableBlockNumber,,bool processed) = IDepositManager(depositManager).withdrawalRequest(layer2Address, address(this), i);
      if(withdrawableBlockNumber <= block.number && !processed) {
          count++;
      }
  }
  return count;
}
```
- called `numWithdrawableRequests`instead of `numPendingRequests` in processWithdrawal functions to get the write number of requests to process.

```Solidity
if(IERC20(ton).balanceOf(address(this)) >= totalClaimableAmount) {
    IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
} else{
    uint256 _numWithdrawableRequests = numWithdrawableRequests();
    if(_numWithdrawableRequests > 0) {               
        if (!IDepositManager(depositManager).processRequests(layer2Address, _numWithdrawableRequests, true)) {
            revert ProcessRequestFailed();
        }
    }
    IERC20(ton).safeTransfer(msg.sender, totalClaimableAmount);
}
```
- created a `processWithdrawalRequest`function to withdraw a specific request in the case of having a large number of requests that are making the `processRequests` function to run out of gas => kind of mitigating the risk of DoS
```Solidity
/**
 * @notice process one or multiple requests. This function can be called by anyone
 */
function processWithdrawalRequest(uint256 numRequests) external returns(bool) {
    if (!IDepositManager(depositManager).processRequests(layer2Address, numRequests, true)) {
            revert ProcessRequestFailed();
    }
    return true;
}
```

I believe that all the risks raised in this issue thread are resolved. @nguyenzung @Zena-park can you check and confirm ? 
Thanks

**Comment by Zena-park** [comment]
It is very difficult to check the code visually to make sure there are no problems.
Please make a test code of the function you created and attach the results.

When I glanced at the above 'function numWithdrawableRequests()',
` IDepositManager(depositManager).withdrawalRequest(layer2Address, address(this), i);`

i value always starts from 0. 
but i is an index(The last executed index), so it seems wrong.

**Comment by mehdi-defiesta** [comment]
@Zena-park Indeed, I forgot to make start from the index. This version works
```Solidity
for(uint256 i = 0; i < numberPendingRequests; ++i) {
    (uint128 withdrawableBlockNumber,,bool processed) = IDepositManager(depositManager).withdrawalRequest(layer2Address, address(this), index  + i);
    if(withdrawableBlockNumber <= block.number && !processed) {
        count++;
    }
}
```

Regarding the testing, [Here](https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/test/L1/L1WrappedStakedTON.t.sol#L581-L646) is a complete scenario of 2 users requesting and claiming at a different time. The test successfully returns the correct value. As for checking if the funds are correctly transferred, There is many tests for it such as `testClaimWithdrawalByTwoDifferentUsers`, `testClaimWithdrawalIndexShouldRevertIfDelayNotElapsed`, `testClaimWithdrawalIndexShouldRevertIfAlreadyProcessed`, `testClaimWithdrawalIndexShouldRevertIfWrongRequestIndex`, `testClaimWithdrawalIndex`, `testClaimWithdrawalTotalShouldRevertIfNoClaimableAmount`, `testClaimWithdrawalTotal`

Finally I forgot to mention but I've implented two  new variables:
```Solidity
mapping(address => uint8) internal numWithdrawalRequestsByUser;
uint8 internal maxNumWithdrawal;
```
Each user cannot request above a maximum limit at a time (for example 5 requests). This threshold is define at the initialization and can be [modified by the owner](https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTON.sol#L142).
Let me know if you need more info

**Comment by Zena-park** [comment]
@mehdi-defiesta Thank you for the detailed explanation. I understand. Thank you.

**Comment by Zena-park** [comment]
In the function _claimWithdrawalIndex(uint256 _index)  
 
https://github.com/tokamak-network/gem-nft-contract/blob/1a477ac9fe0f93dc44d50f703b63843be09ae045/src/L1/L1WrappedStakedTON.sol#L481

When withdrawalRequests[A].length ==3, there are indexes [0,1,2] and  withdrawalRequests[msg.sender][index].processed == false,
  
If _claimWithdrawalIndex(1) is called, 2 withdrawalRequests will be processed.
Therefore, `numWithdrawalRequestsByUser[msg.sender] --;  ` may be incorrect.

**Comment by mehdi-defiesta** [comment]
@nguyenzung @Zena-park thank you. I close the issue
