### ISSUE TITLE
[Code review: Contract Bugs]: Duplicate Event

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#78]
### Describe the bug

 StakingIndexUpdated event occurs twice in one transaction.
 
 https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTON.sol#L542
 
 https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTON.sol#L322
 
 https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTON.sol#L384
 
 

### Impact

Increase in gas prices

**Comment by mehdi-defiesta** [comment]
yes I deleted the event emit on line 542. It was done to catch a bug and I forgot to remove it.
