### ISSUE TITLE
Set the cooldownDueDate after randomGem is minted

### ISSUE THREAD

**Issue by jusdy** [tokamak-network/gem-nft-contract#89]
we have to set the cooldownDueDate of the gem which will be minted after randomGemPack function
currently we have two types of events emitted when the randomGem is minted, one is RandomGemTransferred which is the case when there is any gem available in treasury and CommonGemMinted event which is the case when there is no gem in treasury
I think adding cooldownDueDate to those two params are a bit annoying on contract logic side so to implement this consistently on every gems' cases, i think we need to make a new event with tokenId, cooldownDueDate, etc inside transferTreasuryGEMto function as all the gems transferred from treasury to users must reset the cooldown in every cases

Please let me know if this doesn't make sense so we can have a deeper discuss

**Comment by mehdi-defiesta** [comment]
after discussion, here is the updated code : https://github.com/tokamak-network/gem-nft-contract/commit/ae84834591c14564ce0dff20e534637241221575
