### ISSUE TITLE
Add a cooldownDueDate of the original gem after mining

### ISSUE THREAD

**Issue by jusdy** [tokamak-network/gem-nft-contract#90]
Currently we have an event inside fulFillRandomWords function after pickMinedGem
https://github.com/tokamak-network/gem-nft-contract/blob/2637d480cea37a7de5aaf214e7af108df8d9a073/src/L2/GemFactoryMining.sol#L240

I think we have to add a cooldownDueDate of the original mining gem as soon as the mining is finished

**Comment by mehdi-defiesta** [comment]
after discussion, here is the updated code : https://github.com/tokamak-network/gem-nft-contract/commit/ae84834591c14564ce0dff20e534637241221575
